<?php

class Home extends CI_Controller
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->load->model('product_model','pro');
        $this->load->model('Slider_model','slider');
        $this->load->model("category_model","cat");
        $this->load->model("blog_model","blog");
        $this->load->model("banner_model","banner");
        $this->load->model("testimonial_model","testimonial");
        $this->load->model("spotlight_model","spotlight");
        $this->load->helper('text');
        $this->load->library('cart');
        $this->load->library('wishlist');
        $this->load->library('compare');
        $this->load->library('user_agent');
    }

    function index(){


        $d['link'] = "?";
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
            $cat->pro = $this->pro->getProList($cat->id  , "id , title , image  ,  discount"  );
        }
        $d['topdeals']  = $this->pro->getHomeWithDetails($this->pro->todaydeals);
   
        $d['popular']  = $this->pro->getHomeWithDetails($this->pro->popular_product,4);
        $d['banners'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 3 ) , false , null , array('order_by'=>'order_no DESC') );
        $d['banners_top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 2 ) , 4 , null , array('order_by'=>'order_no DESC') );
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['blogs'] = $this->blog->getBy(array( 'status'=>1 ) , false , null , array('order_by'=>'order_no DESC') );

       /* $new  = $this->pro->getHome($this->pro->new_arrivals);
        foreach($new as $r )
            $d['new_arrivals'][] = $r->id ;
        $new  = $this->pro->getHome($this->pro->accessories);
        foreach($new as $r )
            $d['accessories'][] = $r->id ;*/



        $d['slider'] = $this->slider->getRecords();


        $this->load->view('home',$d);
    }

    function contact(){
		$d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') ); 
        if(isset($_POST['email'])):

            $name = $_POST['name'];
            $email = $_POST['email'];
            $subject = $_POST['subject'];
            $message = $_POST['message']; 
 
            $e_subject = 'You Have Received a Message From ' . $name . '.';

            if(!empty($subject))
            {
                $e_subject = $subject . '.';
            }

            $e_body = 	"You have Received a message from: "
                .$name
                . "\n"
                ."Their additional message is as follows."
                ."\r\n\n";

            $e_content = "\" $message \"\r\n\n";

            $e_reply = 	"You can contact "
                .$name
                . " via email, "
                .$email;

            $msg = $e_body . $e_content . $e_reply;

            $this->load->library('email');
            //$config['mailtype'] = 'html';
           // $this->email->initialize($config);
            $this->email->from(EMAIL, PROJECT_TITLE);
            $this->email->to( $email );
            $this->email->subject($subject);
            $this->email->message($msg);

            if( $this->email->send())
            {
                $this->session->set_flashdata('valid', "Message Sent Successfully!");
            }
            else
            {
                $this->session->set_flashdata('error', 'Message Sent Failure !!!');
            }
        endif;

        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }

        $this->load->view('contact',$d);
    }

    function about(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view('about',$d);
    }
	
	function Buyer_Guide(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view('buyers_guide',$d);
    }

    function policy(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view('privacy_policy',$d);
    }

    function Copyrights(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view('copyright',$d);
    }

    function terms(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view('terms_conditions',$d);
    }

    function Warranty(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view('warranty',$d);
    }

    function Quality(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view('quality',$d);
    }

    function Security(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view('security',$d);
    }

    function Delivery_Information(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view('delivery_information',$d);
    }

    function returns(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view('return',$d);
    }


    function subscribe(){

        $str = $this->input->get('email');

        if (function_exists('idn_to_ascii') && $atpos = strpos($str, '@'))
        {
            $str = substr($str, 0, ++$atpos).idn_to_ascii(substr($str, $atpos));
        }


        if ( (bool) filter_var($str, FILTER_VALIDATE_EMAIL) ){
            echo json_encode($this->db->insert('subscribe',$this->input->get()) ? array("success"=> "Thank you For Subscribe US") : array("success"=>"Your Already Subscribed"));
        }else{
            echo json_encode( array("success"=> "Invalid email" ) );
        }
    }

    function services(){
        $d['type'] = $this->type->getRecords();
        $this->load->view('services',$d);
    }

    function changeCurrency($to){
        $this->session->set_userdata('from',$to);
    }

    function blog(){
       $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $d['popular']  = $this->pro->getHomeWithDetails($this->pro->new_arrivals,4);
		
        $d['limit']   = $this->input->get('limit') ?  $this->input->get('limit') : LIMIT ;
        $page = array(   $d['limit'] ,   $d['limit']  * ( ($this->input->get('page_id')? $this->input->get('page_id') : 1)  - 1 ) )  ;
         
        $d['blogs'] = $this->blog->getBy(array('status'=>1),$page);
        $this->load->view("blog",$d);

    }

    function blog_detail($id){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $d['popular']  = $this->pro->getHomeWithDetails($this->pro->new_arrivals,4);
        $d['blog'] = $this->blog->getBy(array('id'=>$id),1);
        if(!is_object($d['blog'])) show_404();
        $this->load->view("blog_detail",$d);
    }

    function spotlight(){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }

        $d['limit']   = $this->input->get('limit') ?  $this->input->get('limit') : LIMIT ;
        $page = array(   $d['limit'] ,   $d['limit']  * ( ($this->input->get('page_id')? $this->input->get('page_id') : 1)  - 1 ) )  ;
        $d['top']  = $this->pro->getHomeWithDetails($this->pro->recommended);

        $d['blogs'] = $this->spotlight->getBy(array('status'=>1),$page);
        $this->load->view("spotlight",$d);

    }

    function spotlight_detail($id){
        $d['top'] = $this->banner->getBy(array( 'status'=>1 , 'position' => 1 ) , 1 , null , array('order_by'=>'id DESC') );
        $d['top']  = $this->pro->getHomeWithDetails($this->pro->recommended);
        $d['blog'] = $this->spotlight->getBy(array('id'=>$id),1);
        if(!is_object($d['blog'])) show_404();
        $this->load->view("spotlight_detail",$d);
    }

    function error_page(){
        $d['category'] = $this->cat->getBy(array('status ' => 1 ,"category_id" => 0 ) , null , "id,title,short,image,icon" );
        foreach($d['category'] as &$cat  ) {
            $cat->sub = $this->cat->getBy(array('status' => 1 ,"category_id" => $cat->id ) , null , "id,title"  );
        }
        $this->load->view("error_404",$d);
    }

}