<?php

/**
 * Created by PhpStorm.
 * User: Gowtham
 * Date: 2/19/2016
 * Time: 9:58 AM
 */
class Category extends MY_Controller
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->_checkLogin();
        $this->load->model("category_model","model");
    }


    function index(){
        $d['id'] = $this->input->get('category_id') ?  $this->input->get('category_id') : 0 ;
        $d['records'] = $this->model->getBy(array('status !=' => 2 , "category_id" => $d['id'] ));
        $this->load->view('admin/category_list' , $d );
    }

    function create(){
        $id = $this->input->get('category_id') ?  $this->input->get('category_id') : 0 ;
        $this->form_validation->set_rules('form[title]', 'Name', 'required');

        if ($this->form_validation->run() == TRUE){
            if($this->model->create()){
                $this->session->set_flashdata('valid', 'Record Inserted Successfully');
            }else{
                $this->session->set_flashdata('error', 'Record Insert Failure !!!');
            }
            redirect(current_url().( $id ? "?category_id=$id" : "" ));
        }else{
            if($this->input->post()){
                $this->session->set_flashdata('error', validation_errors() );
                $d['result'] = (object)$this->input->post('form');
                foreach($this->input->post('image') as $image ){
                    $d['images'][] = (object) array('image'=>$image);
                }
            }
        }
        $this->load->view('admin/category_create' , $d );
    }

    function edit($id=0){
        $this->form_validation->set_rules('form[title]', 'Name', 'required');
        if ($this->form_validation->run() == TRUE){
            $this->model->id = $id ;
            if($this->model->update( $this->input->post('form') , "id=$id" ) && $this->model->insertMoreImage() ){
				//$this->db->update('product_category',['status'=>$this->input->post('form[status]')] , ['cat_id' => $id] );
				
                $this->session->set_flashdata('valid', 'Record Inserted Successfully');
            }else{
                $this->session->set_flashdata('error', 'Record Insert Failure !!!');
            }
            redirect(current_url());
        }else{
            if($this->input->post()){
                $this->session->set_flashdata('error', validation_errors() );
                $d['result'] = (object)$this->input->post('form');
                foreach($this->input->post('image') as $image ){
                    $d['images'][] = (object) array('image'=>$image);
                }
            }
        }

        $d['result'] = $this->model->getBy(array('id'=> $id ) , 1 );
        if(! is_object($d['result']))  show_404();

        $d['images'] = $this->model->getMoreImages($id);

        $this->load->view('admin/category_create' , $d );
    }

    function autoComplete(){
        echo json_encode( $this->model->getMenuList( $this->input->get('str') ) );
    }

    function rearrange(){

        if($this->input->is_ajax_request() ) {
            foreach ($this->input->post('order') as $order_no => $id )
                $this->db->update($this->model->table , array( 'order_no' => $order_no +1) , array('id' => $id) );
            exit;
        }

        $d['id'] = $this->input->get('category_id') ?  $this->input->get('category_id') : 0 ;
        $d['records'] = $this->db->from($this->model->table)
            ->where(array('status ' => 1  , "category_id" => $d['id'] ))
            ->order_by('order_no')->get()->result(); 
        $this->load->view('admin/category_rearrange' , $d );
    }

    function subMenu(){
        $categoryId = $this->input->get_post('category_id') ? $this->input->get_post('category_id') : 0 ;

        $categories = $this->model->getBy(array('status' =>1  , "category_id" =>$categoryId),null, "id,title");
        if($this->input->is_ajax_request()){
            echo json_encode($categories);
        }

    }

}